INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Jean', 'Mugabo', 'O+', TO_DATE('1985-03-12', 'YYYY-MM-DD'), 'M', '0788111111', 'jean.m@email.com', 'Kigali, Gasabo', SYSDATE-100, SYSDATE-10, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Alice', 'Uwase', 'A+', TO_DATE('1990-07-22', 'YYYY-MM-DD'), 'F', '0788222222', 'alice.u@email.com', 'Kigali, Kicukiro', SYSDATE-90, SYSDATE-20, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Eric', 'Nshuti', 'B-', TO_DATE('1988-11-05', 'YYYY-MM-DD'), 'M', '0788333333', 'eric.n@email.com', 'Kigali, Nyarugenge', SYSDATE-80, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Claire', 'Mutesi', 'O-', TO_DATE('1995-02-14', 'YYYY-MM-DD'), 'F', '0788444444', 'claire.m@email.com', 'Musanze', SYSDATE-200, SYSDATE-60, 'DEFERRED', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Patrick', 'Kwizera', 'AB+', TO_DATE('1982-09-30', 'YYYY-MM-DD'), 'M', '0788555555', 'pat.k@email.com', 'Rubavu', SYSDATE-150, SYSDATE-90, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Divine', 'Ingabire', 'A-', TO_DATE('1993-05-18', 'YYYY-MM-DD'), 'F', '0788666666', 'divine.i@email.com', 'Huye', SYSDATE-60, SYSDATE-5, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Fabrice', 'Manzi', 'O+', TO_DATE('1987-12-25', 'YYYY-MM-DD'), 'M', '0788777777', 'fab.m@email.com', 'Rwamagana', SYSDATE-300, SYSDATE-120, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Sarah', 'Umutoni', 'B+', TO_DATE('1998-04-01', 'YYYY-MM-DD'), 'F', '0788888888', 'sarah.u@email.com', 'Kayonza', SYSDATE-40, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'David', 'Habimana', 'AB-', TO_DATE('1991-08-15', 'YYYY-MM-DD'), 'M', '0788999999', 'david.h@email.com', 'Kigali, Gasabo', SYSDATE-10, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Grace', 'Mukamana', 'O+', TO_DATE('1989-01-10', 'YYYY-MM-DD'), 'F', '0788101010', 'grace.m@email.com', 'Kigali, Kicukiro', SYSDATE-400, SYSDATE-30, 'PERMANENT_DEFERRED', 'N');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Paul', 'Rwigema', 'A+', TO_DATE('1980-06-20', 'YYYY-MM-DD'), 'M', '0788121212', 'paul.r@email.com', 'Gicumbi', SYSDATE-50, SYSDATE-15, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Sonia', 'Iribagiza', 'B-', TO_DATE('1994-10-10', 'YYYY-MM-DD'), 'F', '0788131313', 'sonia.i@email.com', 'Muhanga', SYSDATE-75, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Moses', 'Bizimana', 'O-', TO_DATE('1986-03-03', 'YYYY-MM-DD'), 'M', '0788141414', 'moses.b@email.com', 'Nyanza', SYSDATE-120, SYSDATE-40, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Olive', 'Akamanzi', 'AB+', TO_DATE('1992-07-07', 'YYYY-MM-DD'), 'F', '0788151515', 'olive.a@email.com', 'Rusizi', SYSDATE-180, SYSDATE-100, 'DEFERRED', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Frank', 'Gatete', 'A-', TO_DATE('1984-11-22', 'YYYY-MM-DD'), 'M', '0788161616', 'frank.g@email.com', 'Karongi', SYSDATE-95, SYSDATE-10, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Diane', 'Uwimana', 'O+', TO_DATE('1996-09-09', 'YYYY-MM-DD'), 'F', '0788171717', 'diane.u@email.com', 'Kigali, Gasabo', SYSDATE-25, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Claude', 'Ndayisaba', 'B+', TO_DATE('1983-05-05', 'YYYY-MM-DD'), 'M', '0788181818', 'claude.n@email.com', 'Kigali, Nyarugenge', SYSDATE-365, SYSDATE-200, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Beatrice', 'Nyiramongana', 'AB-', TO_DATE('1990-01-30', 'YYYY-MM-DD'), 'F', '0788191919', 'bea.n@email.com', 'Nyagatare', SYSDATE-55, SYSDATE-5, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'James', 'Rutayisire', 'O-', TO_DATE('1981-12-12', 'YYYY-MM-DD'), 'M', '0788202020', 'james.r@email.com', 'Bugesera', SYSDATE-20, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Aline', 'Mukandayisenga', 'A+', TO_DATE('1997-02-18', 'YYYY-MM-DD'), 'F', '0788212121', 'aline.m@email.com', 'Kigali, Kicukiro', SYSDATE-10, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Robert', 'Gasana', 'O+', TO_DATE('1985-06-15', 'YYYY-MM-DD'), 'M', '0788222324', 'robert.g@email.com', 'Kigali, Gasabo', SYSDATE-300, SYSDATE-90, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Sandrine', 'Isimbi', 'B+', TO_DATE('1993-08-20', 'YYYY-MM-DD'), 'F', '0788252627', 'sandrine.i@email.com', 'Musanze', SYSDATE-150, SYSDATE-50, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Peter', 'Musoni', 'A-', TO_DATE('1989-11-11', 'YYYY-MM-DD'), 'M', '0788282930', 'peter.m@email.com', 'Rubavu', SYSDATE-40, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Josiane', 'Mukashema', 'AB+', TO_DATE('1991-03-25', 'YYYY-MM-DD'), 'F', '0788313233', 'josiane.m@email.com', 'Huye', SYSDATE-200, SYSDATE-30, 'DEFERRED', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Emmanuel', 'Ngarambe', 'O-', TO_DATE('1980-07-07', 'YYYY-MM-DD'), 'M', '0788343536', 'emma.n@email.com', 'Rwamagana', SYSDATE-500, SYSDATE-10, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Nadia', 'Umuhoza', 'A+', TO_DATE('1995-12-05', 'YYYY-MM-DD'), 'F', '0788373839', 'nadia.u@email.com', 'Kigali, Nyarugenge', SYSDATE-60, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Richard', 'Karegeya', 'B-', TO_DATE('1987-04-14', 'YYYY-MM-DD'), 'M', '0788404142', 'richard.k@email.com', 'Kigali, Gasabo', SYSDATE-80, SYSDATE-20, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Clementine', 'Mukarugwiza', 'O+', TO_DATE('1990-09-09', 'YYYY-MM-DD'), 'F', '0788434445', 'clem.m@email.com', 'Gicumbi', SYSDATE-100, SYSDATE-40, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Theoneste', 'Bagirishya', 'AB-', TO_DATE('1982-01-20', 'YYYY-MM-DD'), 'M', '0788464748', 'theo.b@email.com', 'Nyanza', SYSDATE-90, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Solange', 'Umulisa', 'A+', TO_DATE('1994-05-30', 'YYYY-MM-DD'), 'F', '0788495051', 'solange.u@email.com', 'Rusizi', SYSDATE-30, SYSDATE-5, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Bosco', 'Ntaganda', 'O+', TO_DATE('1986-10-15', 'YYYY-MM-DD'), 'M', '0788525354', 'bosco.n@email.com', 'Karongi', SYSDATE-250, SYSDATE-100, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Esther', 'Mbabazi', 'B+', TO_DATE('1992-02-28', 'YYYY-MM-DD'), 'F', '0788555657', 'esther.m@email.com', 'Nyagatare', SYSDATE-45, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Gedeon', 'Nshimiyimana', 'A-', TO_DATE('1988-06-18', 'YYYY-MM-DD'), 'M', '0788585960', 'gedeon.n@email.com', 'Bugesera', SYSDATE-120, SYSDATE-60, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Fanny', 'Uwera', 'AB+', TO_DATE('1996-11-25', 'YYYY-MM-DD'), 'F', '0788616263', 'fanny.u@email.com', 'Kigali, Kicukiro', SYSDATE-20, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Innocent', 'Kamanzi', 'O-', TO_DATE('1984-03-08', 'YYYY-MM-DD'), 'M', '0788646566', 'innocent.k@email.com', 'Musanze', SYSDATE-300, SYSDATE-150, 'DEFERRED', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Juliette', 'Murekatete', 'A+', TO_DATE('1990-08-12', 'YYYY-MM-DD'), 'F', '0788676869', 'juliette.m@email.com', 'Rubavu', SYSDATE-70, SYSDATE-10, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Albert', 'Rudasingwa', 'B-', TO_DATE('1981-12-30', 'YYYY-MM-DD'), 'M', '0788707172', 'albert.r@email.com', 'Huye', SYSDATE-400, SYSDATE-10, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Chantal', 'Uwineza', 'O+', TO_DATE('1993-05-05', 'YYYY-MM-DD'), 'F', '0788737475', 'chantal.u@email.com', 'Rwamagana', SYSDATE-50, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Felix', 'Mugisha', 'AB-', TO_DATE('1989-09-20', 'YYYY-MM-DD'), 'M', '0788767778', 'felix.m@email.com', 'Kayonza', SYSDATE-90, SYSDATE-30, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Yvonne', 'Mukantwari', 'A+', TO_DATE('1995-01-15', 'YYYY-MM-DD'), 'F', '0788798081', 'yvonne.m@email.com', 'Kigali, Gasabo', SYSDATE-15, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Eugene', 'Nsabimana', 'B+', TO_DATE('1983-06-10', 'YYYY-MM-DD'), 'M', '0788828384', 'eugene.n@email.com', 'Gicumbi', SYSDATE-180, SYSDATE-80, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Nicole', 'Irakoze', 'O-', TO_DATE('1991-10-25', 'YYYY-MM-DD'), 'F', '0788858687', 'nicole.i@email.com', 'Nyanza', SYSDATE-60, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Aimable', 'Twahirwa', 'AB+', TO_DATE('1987-02-02', 'YYYY-MM-DD'), 'M', '0788888990', 'aimable.t@email.com', 'Rusizi', SYSDATE-200, SYSDATE-50, 'PERMANENT_DEFERRED', 'N');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Gloria', 'Uwamahoro', 'A-', TO_DATE('1994-07-18', 'YYYY-MM-DD'), 'F', '0788919293', 'gloria.u@email.com', 'Karongi', SYSDATE-30, SYSDATE-5, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Olivier', 'Hategekimana', 'O+', TO_DATE('1985-11-30', 'YYYY-MM-DD'), 'M', '0788949596', 'olivier.h@email.com', 'Nyagatare', SYSDATE-100, SYSDATE-20, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Carine', 'Ineza', 'B-', TO_DATE('1992-04-12', 'YYYY-MM-DD'), 'F', '0788979899', 'carine.i@email.com', 'Bugesera', SYSDATE-50, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Samuel', 'Bigirimana', 'AB-', TO_DATE('1988-08-28', 'YYYY-MM-DD'), 'M', '0789000102', 'samuel.b@email.com', 'Kigali, Kicukiro', SYSDATE-80, SYSDATE-40, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Ange', 'Kagoyire', 'A+', TO_DATE('1996-12-15', 'YYYY-MM-DD'), 'F', '0789030405', 'ange.k@email.com', 'Kigali, Nyarugenge', SYSDATE-10, NULL, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Ernest', 'Rukundo', 'O+', TO_DATE('1980-05-20', 'YYYY-MM-DD'), 'M', '0789060708', 'ernest.r@email.com', 'Musanze', SYSDATE-250, SYSDATE-100, 'ELIGIBLE', 'Y');
INSERT INTO donors VALUES (seq_donors.NEXTVAL, 'Honorine', 'Mutoni', 'B+', TO_DATE('1990-09-05', 'YYYY-MM-DD'), 'F', '0789091011', 'honorine.m@email.com', 'Rubavu', SYSDATE-40, NULL, 'ELIGIBLE', 'Y');
COMMIT;

INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1001, 'O+', SYSDATE-10, SYSDATE+25, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-10);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1002, 'A+', SYSDATE-20, SYSDATE+15, 470, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-20);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1003, 'B-', SYSDATE-2, SYSDATE+33, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-2);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1004, 'O-', SYSDATE-60, SYSDATE-25, 450, 'EXPIRED', 'PASSED', 'Disposal', SYSDATE-60);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1005, 'AB+', SYSDATE-5, SYSDATE+30, 460, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1006, 'A-', SYSDATE-5, SYSDATE+30, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1007, 'O+', SYSDATE-1, SYSDATE+34, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-1);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1008, 'B+', SYSDATE-40, SYSDATE-5, 480, 'EXPIRED', 'PASSED', 'Disposal', SYSDATE-40);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1009, 'AB-', SYSDATE-12, SYSDATE+23, 450, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-12);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1010, 'O+', SYSDATE-30, SYSDATE+5, 450, 'ISSUED', 'PASSED', 'Dispatch', SYSDATE-30);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1011, 'A+', SYSDATE-15, SYSDATE+20, 455, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-15);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1012, 'B-', SYSDATE-3, SYSDATE+32, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-3);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1013, 'O-', SYSDATE-18, SYSDATE+17, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-18);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1014, 'AB+', SYSDATE-22, SYSDATE+13, 465, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-22);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1015, 'A-', SYSDATE-10, SYSDATE+25, 450, 'ISSUED', 'PASSED', 'Dispatch', SYSDATE-10);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1016, 'O+', SYSDATE-8, SYSDATE+27, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-8);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1017, 'B+', SYSDATE-50, SYSDATE-15, 450, 'DISCARDED', 'FAILED', 'Biohazard', SYSDATE-50);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1018, 'AB-', SYSDATE-5, SYSDATE+30, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1019, 'O-', SYSDATE-14, SYSDATE+21, 490, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-14);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1020, 'A+', SYSDATE-4, SYSDATE+31, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-4);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1021, 'O+', SYSDATE-10, SYSDATE+25, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-10);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1022, 'B+', SYSDATE-25, SYSDATE+10, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-25);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1023, 'A-', SYSDATE-5, SYSDATE+30, 475, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1024, 'AB+', SYSDATE-28, SYSDATE+7, 450, 'ISSUED', 'PASSED', 'Dispatch', SYSDATE-28);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1025, 'O-', SYSDATE-10, SYSDATE+25, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-10);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1026, 'A+', SYSDATE-35, SYSDATE, 450, 'EXPIRED', 'PASSED', 'Disposal', SYSDATE-35);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1027, 'B-', SYSDATE-12, SYSDATE+23, 460, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-12);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1028, 'O+', SYSDATE-7, SYSDATE+28, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-7);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1029, 'AB-', SYSDATE-20, SYSDATE+15, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-20);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1030, 'A+', SYSDATE-5, SYSDATE+30, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1031, 'O+', SYSDATE-45, SYSDATE-10, 450, 'DISCARDED', 'FAILED', 'Biohazard', SYSDATE-45);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1032, 'B+', SYSDATE-9, SYSDATE+26, 455, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-9);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1033, 'A-', SYSDATE-18, SYSDATE+17, 450, 'ISSUED', 'PASSED', 'Dispatch', SYSDATE-18);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1034, 'AB+', SYSDATE-2, SYSDATE+33, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-2);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1035, 'O-', SYSDATE-15, SYSDATE+20, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-15);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1036, 'A+', SYSDATE-10, SYSDATE+25, 470, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-10);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1037, 'B-', SYSDATE-5, SYSDATE+30, 450, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1038, 'O+', SYSDATE-30, SYSDATE+5, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-30);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1039, 'AB-', SYSDATE-3, SYSDATE+32, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-3);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1040, 'A+', SYSDATE-12, SYSDATE+23, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-12);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1041, 'O+', SYSDATE-60, SYSDATE-25, 450, 'EXPIRED', 'PASSED', 'Disposal', SYSDATE-60);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1042, 'B+', SYSDATE-8, SYSDATE+27, 460, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-8);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1043, 'AB+', SYSDATE-22, SYSDATE+13, 450, 'ISSUED', 'PASSED', 'Dispatch', SYSDATE-22);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1044, 'A-', SYSDATE-16, SYSDATE+19, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-16);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1045, 'O-', SYSDATE-5, SYSDATE+30, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-5);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1046, 'B-', SYSDATE-40, SYSDATE-5, 450, 'DISCARDED', 'FAILED', 'Biohazard', SYSDATE-40);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1047, 'AB-', SYSDATE-10, SYSDATE+25, 480, 'AVAILABLE', 'PASSED', 'Fridge 2', SYSDATE-10);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1048, 'A+', SYSDATE-2, SYSDATE+33, 450, 'TESTING', 'PENDING', 'Quarantine', SYSDATE-2);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1049, 'O+', SYSDATE-25, SYSDATE+10, 450, 'AVAILABLE', 'PASSED', 'Fridge 3', SYSDATE-25);
INSERT INTO blood_units VALUES (seq_blood_units.NEXTVAL, 1050, 'B+', SYSDATE-15, SYSDATE+20, 450, 'AVAILABLE', 'PASSED', 'Fridge 1', SYSDATE-15);
COMMIT;

INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Marcel', 'Twagira', 'O+', TO_DATE('1975-01-01', 'YYYY-MM-DD'), 'M', '0780000001', 'Wife: 0780000002', 'Hypertension', SYSDATE-10);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Angelique', 'Mukazitoni', 'A-', TO_DATE('1982-05-15', 'YYYY-MM-DD'), 'F', '0780000003', 'Husband: 0780000004', 'Anemia', SYSDATE-20);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Jean', 'Nshimiyimana', 'B+', TO_DATE('1990-11-20', 'YYYY-MM-DD'), 'M', '0780000005', 'Father: 0780000006', 'Surgery Recovery', SYSDATE-5);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Claudine', 'Mutesi', 'AB+', TO_DATE('2000-03-10', 'YYYY-MM-DD'), 'F', '0780000007', 'Mother: 0780000008', 'Car Accident', SYSDATE-2);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Bosco', 'Gatete', 'O-', TO_DATE('1965-08-30', 'YYYY-MM-DD'), 'M', '0780000009', 'Son: 0780000010', 'Leukemia', SYSDATE-15);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Fatuma', 'Nyiraneza', 'A+', TO_DATE('1995-12-12', 'YYYY-MM-DD'), 'F', '0780000011', 'Sister: 0780000012', 'Childbirth', SYSDATE-1);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Patrick', 'Iradukunda', 'B-', TO_DATE('1988-06-25', 'YYYY-MM-DD'), 'M', '0780000013', 'Brother: 0780000014', 'Malaria severe', SYSDATE-3);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Chantal', 'Umuhire', 'AB-', TO_DATE('1992-09-09', 'YYYY-MM-DD'), 'F', '0780000015', 'Friend: 0780000016', 'Cancer Treatment', SYSDATE-30);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Eric', 'Mugisha', 'O+', TO_DATE('1998-02-18', 'YYYY-MM-DD'), 'M', '0780000017', 'Uncle: 0780000018', 'Trauma', SYSDATE-4);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Rose', 'Akanyana', 'A-', TO_DATE('1970-07-07', 'YYYY-MM-DD'), 'F', '0780000019', 'Daughter: 0780000020', 'Kidney Failure', SYSDATE-12);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Didier', 'Shema', 'B+', TO_DATE('1985-04-14', 'YYYY-MM-DD'), 'M', '0780000021', 'Wife: 0780000022', 'Surgery', SYSDATE-8);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Florence', 'Ishimwe', 'O+', TO_DATE('1991-10-30', 'YYYY-MM-DD'), 'F', '0780000023', 'Mother: 0780000024', 'Anemia', SYSDATE-25);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Augustin', 'Ndayambaje', 'AB+', TO_DATE('1960-01-20', 'YYYY-MM-DD'), 'M', '0780000025', 'Son: 0780000026', 'Heart Surgery', SYSDATE-10);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Marie', 'Claire', 'O-', TO_DATE('1999-05-05', 'YYYY-MM-DD'), 'F', '0780000027', 'Father: 0780000028', 'Accident', SYSDATE-1);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Theophile', 'Habimana', 'A+', TO_DATE('1978-11-11', 'YYYY-MM-DD'), 'M', '0780000029', 'Wife: 0780000030', 'Ulcer', SYSDATE-6);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Solange', 'Uwingabire', 'B-', TO_DATE('1986-08-08', 'YYYY-MM-DD'), 'F', '0780000031', 'Husband: 0780000032', 'Complications', SYSDATE-3);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Innocent', 'Ruzibiza', 'AB-', TO_DATE('1993-02-22', 'YYYY-MM-DD'), 'M', '0780000033', 'Brother: 0780000034', 'Surgery', SYSDATE-15);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Jeannette', 'Mukamurenzi', 'O+', TO_DATE('1980-12-01', 'YYYY-MM-DD'), 'F', '0780000035', 'Sister: 0780000036', 'Cancer', SYSDATE-40);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Fabien', 'Kagabo', 'A-', TO_DATE('1972-03-15', 'YYYY-MM-DD'), 'M', '0780000037', 'Son: 0780000038', 'Accident', SYSDATE-7);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Lydia', 'Uwimbabazi', 'B+', TO_DATE('1994-06-30', 'YYYY-MM-DD'), 'F', '0780000039', 'Mother: 0780000040', 'Childbirth', SYSDATE-2);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Gilbert', 'Ndahiro', 'AB+', TO_DATE('1984-09-18', 'YYYY-MM-DD'), 'M', '0780000041', 'Father: 0780000042', 'Malaria', SYSDATE-9);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Odette', 'Nyirabagenzi', 'O-', TO_DATE('1968-04-25', 'YYYY-MM-DD'), 'F', '0780000043', 'Daughter: 0780000044', 'Anemia', SYSDATE-11);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Samuel', 'Mugwaneza', 'A+', TO_DATE('1997-01-10', 'YYYY-MM-DD'), 'M', '0780000045', 'Uncle: 0780000046', 'Surgery', SYSDATE-5);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Yvette', 'Keza', 'B-', TO_DATE('2001-11-05', 'YYYY-MM-DD'), 'F', '0780000047', 'Aunt: 0780000048', 'Sickle Cell', SYSDATE-20);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Martin', 'Bimenyimana', 'AB-', TO_DATE('1976-07-20', 'YYYY-MM-DD'), 'M', '0780000049', 'Wife: 0780000050', 'Trauma', SYSDATE-3);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Francine', 'Mukandayisenga', 'O+', TO_DATE('1989-10-15', 'YYYY-MM-DD'), 'F', '0780000051', 'Sister: 0780000052', 'Surgery', SYSDATE-18);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Alain', 'Ngabo', 'A-', TO_DATE('1983-02-28', 'YYYY-MM-DD'), 'M', '0780000053', 'Friend: 0780000054', 'Accident', SYSDATE-1);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Beata', 'Umutesi', 'B+', TO_DATE('1990-05-12', 'YYYY-MM-DD'), 'F', '0780000055', 'Husband: 0780000056', 'Childbirth', SYSDATE-4);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Charles', 'Karangwa', 'AB+', TO_DATE('1974-08-08', 'YYYY-MM-DD'), 'M', '0780000057', 'Son: 0780000058', 'Heart', SYSDATE-15);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Denise', 'Uwase', 'O-', TO_DATE('1996-12-30', 'YYYY-MM-DD'), 'F', '0780000059', 'Mother: 0780000060', 'Anemia', SYSDATE-25);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Edouard', 'Munyakazi', 'A+', TO_DATE('1981-03-20', 'YYYY-MM-DD'), 'M', '0780000061', 'Brother: 0780000062', 'Surgery', SYSDATE-6);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Fiona', 'Iribagiza', 'B-', TO_DATE('1998-09-02', 'YYYY-MM-DD'), 'F', '0780000063', 'Father: 0780000064', 'Malaria', SYSDATE-10);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Gaston', 'Nizeyimana', 'AB-', TO_DATE('1987-01-14', 'YYYY-MM-DD'), 'M', '0780000065', 'Wife: 0780000066', 'Accident', SYSDATE-2);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Helene', 'Mukaruzima', 'O+', TO_DATE('1963-06-18', 'YYYY-MM-DD'), 'F', '0780000067', 'Son: 0780000068', 'Surgery', SYSDATE-20);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Ivan', 'Gasore', 'A-', TO_DATE('1992-11-25', 'YYYY-MM-DD'), 'M', '0780000069', 'Friend: 0780000070', 'Trauma', SYSDATE-1);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Jacky', 'Uwamwezi', 'B+', TO_DATE('1985-04-05', 'YYYY-MM-DD'), 'F', '0780000071', 'Husband: 0780000072', 'Childbirth', SYSDATE-3);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Kevin', 'Mugabo', 'AB+', TO_DATE('1995-07-22', 'YYYY-MM-DD'), 'M', '0780000073', 'Father: 0780000074', 'Surgery', SYSDATE-12);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Leonie', 'Mukamabano', 'O-', TO_DATE('1979-10-10', 'YYYY-MM-DD'), 'F', '0780000075', 'Sister: 0780000076', 'Anemia', SYSDATE-30);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Maurice', 'Twagirayezu', 'A+', TO_DATE('1969-02-15', 'YYYY-MM-DD'), 'M', '0780000077', 'Son: 0780000078', 'Cancer', SYSDATE-60);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Nadine', 'Isimbi', 'B-', TO_DATE('1993-05-28', 'YYYY-MM-DD'), 'F', '0780000079', 'Mother: 0780000080', 'Surgery', SYSDATE-7);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Oscar', 'Nsengiyumva', 'AB-', TO_DATE('1986-08-12', 'YYYY-MM-DD'), 'M', '0780000081', 'Wife: 0780000082', 'Accident', SYSDATE-5);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Pacifique', 'Tuyisenge', 'O+', TO_DATE('1999-12-05', 'YYYY-MM-DD'), 'M', '0780000083', 'Brother: 0780000084', 'Malaria', SYSDATE-2);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Queen', 'Mutesi', 'A-', TO_DATE('1991-03-30', 'YYYY-MM-DD'), 'F', '0780000085', 'Husband: 0780000086', 'Sickle Cell', SYSDATE-15);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Remy', 'Dusabe', 'B+', TO_DATE('1982-09-15', 'YYYY-MM-DD'), 'M', '0780000087', 'Wife: 0780000088', 'Surgery', SYSDATE-8);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Sylvie', 'Umugwaneza', 'AB+', TO_DATE('1988-01-25', 'YYYY-MM-DD'), 'F', '0780000089', 'Sister: 0780000090', 'Anemia', SYSDATE-22);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Thomas', 'Hakizimana', 'O-', TO_DATE('1973-06-08', 'YYYY-MM-DD'), 'M', '0780000091', 'Son: 0780000092', 'Cancer', SYSDATE-45);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Ursula', 'Uwambaye', 'A+', TO_DATE('1994-11-18', 'YYYY-MM-DD'), 'F', '0780000093', 'Mother: 0780000094', 'Surgery', SYSDATE-4);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Victor', 'Ndayishimiye', 'B-', TO_DATE('1980-04-22', 'YYYY-MM-DD'), 'M', '0780000095', 'Friend: 0780000096', 'Accident', SYSDATE-1);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Winifred', 'Mukasine', 'AB-', TO_DATE('1997-08-30', 'YYYY-MM-DD'), 'F', '0780000097', 'Father: 0780000098', 'Trauma', SYSDATE-3);
INSERT INTO patients VALUES (seq_patients.NEXTVAL, 'Xavier', 'Mugisha', 'O+', TO_DATE('1989-02-14', 'YYYY-MM-DD'), 'M', '0780000099', 'Brother: 0780000100', 'Malaria', SYSDATE-6);
COMMIT;

INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5001, 'O+', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5002, 'A+', 'REFRIGERATOR_A', 3.5, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5003, 'B-', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5004, 'O-', 'QUARANTINE', 4.2, SYSDATE, 'Tech_B', 'Expired - Remove');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5005, 'AB+', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5006, 'A-', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5007, 'O+', 'QUARANTINE', 3.9, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5008, 'B+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Expired - Remove');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5009, 'AB-', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5010, 'O+', 'REFRIGERATOR_A', 4.1, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5011, 'A+', 'REFRIGERATOR_B', 3.6, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5012, 'B-', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5013, 'O-', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5014, 'AB+', 'REFRIGERATOR_B', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5015, 'A-', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5016, 'O+', 'REFRIGERATOR_B', 4.2, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5017, 'B+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Failed Test');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5018, 'AB-', 'REFRIGERATOR_A', 3.5, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5019, 'O-', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5020, 'A+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5021, 'O+', 'REFRIGERATOR_A', 4.1, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5022, 'B+', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5023, 'A-', 'REFRIGERATOR_A', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5024, 'AB+', 'REFRIGERATOR_B', 4.0, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5025, 'O-', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5026, 'A+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Expired');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5027, 'B-', 'REFRIGERATOR_B', 3.6, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5028, 'O+', 'QUARANTINE', 4.1, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5029, 'AB-', 'REFRIGERATOR_A', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5030, 'A+', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5031, 'O+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Failed Test');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5032, 'B+', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5033, 'A-', 'REFRIGERATOR_B', 4.0, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5034, 'AB+', 'QUARANTINE', 4.2, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5035, 'O-', 'REFRIGERATOR_A', 3.6, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5036, 'A+', 'REFRIGERATOR_B', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5037, 'B-', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5038, 'O+', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5039, 'AB-', 'QUARANTINE', 4.1, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5040, 'A+', 'REFRIGERATOR_A', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5041, 'O+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Expired');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5042, 'B+', 'REFRIGERATOR_B', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5043, 'AB+', 'REFRIGERATOR_A', 3.6, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5044, 'A-', 'REFRIGERATOR_B', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5045, 'O-', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5046, 'B-', 'QUARANTINE', 4.2, SYSDATE, 'Tech_B', 'Failed Test');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5047, 'AB-', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5048, 'A+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5049, 'O+', 'REFRIGERATOR_A', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5050, 'B+', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
COMMIT;

INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5001, 'O+', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5002, 'A+', 'REFRIGERATOR_A', 3.5, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5003, 'B-', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5004, 'O-', 'QUARANTINE', 4.2, SYSDATE, 'Tech_B', 'Expired - Remove');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5005, 'AB+', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5006, 'A-', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5007, 'O+', 'QUARANTINE', 3.9, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5008, 'B+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Expired - Remove');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5009, 'AB-', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5010, 'O+', 'REFRIGERATOR_A', 4.1, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5011, 'A+', 'REFRIGERATOR_B', 3.6, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5012, 'B-', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5013, 'O-', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5014, 'AB+', 'REFRIGERATOR_B', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5015, 'A-', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5016, 'O+', 'REFRIGERATOR_B', 4.2, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5017, 'B+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Failed Test');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5018, 'AB-', 'REFRIGERATOR_A', 3.5, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5019, 'O-', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5020, 'A+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5021, 'O+', 'REFRIGERATOR_A', 4.1, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5022, 'B+', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5023, 'A-', 'REFRIGERATOR_A', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5024, 'AB+', 'REFRIGERATOR_B', 4.0, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5025, 'O-', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5026, 'A+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Expired');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5027, 'B-', 'REFRIGERATOR_B', 3.6, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5028, 'O+', 'QUARANTINE', 4.1, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5029, 'AB-', 'REFRIGERATOR_A', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5030, 'A+', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5031, 'O+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Failed Test');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5032, 'B+', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5033, 'A-', 'REFRIGERATOR_B', 4.0, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5034, 'AB+', 'QUARANTINE', 4.2, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5035, 'O-', 'REFRIGERATOR_A', 3.6, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5036, 'A+', 'REFRIGERATOR_B', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5037, 'B-', 'REFRIGERATOR_A', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5038, 'O+', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5039, 'AB-', 'QUARANTINE', 4.1, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5040, 'A+', 'REFRIGERATOR_A', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5041, 'O+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Expired');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5042, 'B+', 'REFRIGERATOR_B', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5043, 'AB+', 'REFRIGERATOR_A', 3.6, SYSDATE, 'Tech_A', 'Ready for Issue');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5044, 'A-', 'REFRIGERATOR_B', 4.0, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5045, 'O-', 'REFRIGERATOR_A', 3.8, SYSDATE, 'Tech_A', 'Rare Type');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5046, 'B-', 'QUARANTINE', 4.2, SYSDATE, 'Tech_B', 'Failed Test');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5047, 'AB-', 'REFRIGERATOR_B', 3.7, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5048, 'A+', 'QUARANTINE', 4.0, SYSDATE, 'Tech_B', 'Awaiting Tests');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5049, 'O+', 'REFRIGERATOR_A', 3.9, SYSDATE, 'Tech_A', 'Checked OK');
INSERT INTO inventory VALUES (seq_inventory.NEXTVAL, 5050, 'B+', 'REFRIGERATOR_B', 3.8, SYSDATE, 'Tech_A', 'Checked OK');
COMMIT;

INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2001, 5010, SYSDATE-5, 'Dr. Kayumba', 'Ward A', 'Surgery', 'COMPLETED', 'No reaction');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2002, 5015, SYSDATE-10, 'Dr. Mutoni', 'Ward B', 'Anemia', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2003, 5024, SYSDATE-2, 'Dr. Gakwaya', 'ICU', 'Trauma', 'COMPLETED', 'Critical');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2004, 5033, SYSDATE-1, 'Dr. Kayumba', 'Maternity', 'Childbirth', 'IN_PROGRESS', 'Monitoring');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2005, 5043, SYSDATE, 'Dr. Mutoni', 'Ward A', 'Surgery', 'SCHEDULED', 'Pre-op');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2006, 5001, SYSDATE-15, 'Dr. Gakwaya', 'Ward C', 'Malaria', 'COMPLETED', 'Discharged');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2007, 5002, SYSDATE-14, 'Dr. Kayumba', 'Ward A', 'Accident', 'COMPLETED', 'Recovery');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2008, 5005, SYSDATE-12, 'Dr. Mutoni', 'ICU', 'Surgery', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2009, 5006, SYSDATE-10, 'Dr. Gakwaya', 'Ward B', 'Anemia', 'COMPLETED', 'Improved');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2010, 5009, SYSDATE-8, 'Dr. Kayumba', 'Maternity', 'Hemorrhage', 'COMPLETED', 'Critical');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2011, 5011, SYSDATE-6, 'Dr. Mutoni', 'Ward A', 'Surgery', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2012, 5013, SYSDATE-4, 'Dr. Gakwaya', 'Ward C', 'Cancer', 'COMPLETED', 'Ongoing');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2013, 5014, SYSDATE-2, 'Dr. Kayumba', 'ICU', 'Trauma', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2014, 5016, SYSDATE, 'Dr. Mutoni', 'Ward B', 'Surgery', 'IN_PROGRESS', 'Monitoring');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2015, 5018, SYSDATE+1, 'Dr. Gakwaya', 'Ward A', 'Anemia', 'SCHEDULED', 'Prep');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2016, 5019, SYSDATE-20, 'Dr. Kayumba', 'Maternity', 'Childbirth', 'COMPLETED', 'Discharged');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2017, 5021, SYSDATE-18, 'Dr. Mutoni', 'Ward C', 'Malaria', 'COMPLETED', 'Improved');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2018, 5022, SYSDATE-16, 'Dr. Gakwaya', 'Ward A', 'Surgery', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2019, 5023, SYSDATE-14, 'Dr. Kayumba', 'ICU', 'Accident', 'COMPLETED', 'Critical');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2020, 5025, SYSDATE-12, 'Dr. Mutoni', 'Ward B', 'Anemia', 'COMPLETED', 'Improved');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2021, 5027, SYSDATE-10, 'Dr. Gakwaya', 'Maternity', 'Hemorrhage', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2022, 5029, SYSDATE-8, 'Dr. Kayumba', 'Ward A', 'Surgery', 'COMPLETED', 'Recovery');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2023, 5030, SYSDATE-6, 'Dr. Mutoni', 'Ward C', 'Cancer', 'COMPLETED', 'Ongoing');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2024, 5032, SYSDATE-4, 'Dr. Gakwaya', 'ICU', 'Trauma', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2025, 5035, SYSDATE-2, 'Dr. Kayumba', 'Ward B', 'Surgery', 'COMPLETED', 'No reaction');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2026, 5036, SYSDATE, 'Dr. Mutoni', 'Ward A', 'Anemia', 'IN_PROGRESS', 'Slow rate');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2027, 5037, SYSDATE+1, 'Dr. Gakwaya', 'Maternity', 'Childbirth', 'SCHEDULED', 'Prep');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2028, 5038, SYSDATE-25, 'Dr. Kayumba', 'Ward C', 'Malaria', 'COMPLETED', 'Discharged');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2029, 5040, SYSDATE-20, 'Dr. Mutoni', 'Ward A', 'Accident', 'COMPLETED', 'Recovery');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2030, 5042, SYSDATE-15, 'Dr. Gakwaya', 'ICU', 'Surgery', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2031, 5044, SYSDATE-10, 'Dr. Kayumba', 'Ward B', 'Anemia', 'COMPLETED', 'Improved');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2032, 5045, SYSDATE-5, 'Dr. Mutoni', 'Maternity', 'Hemorrhage', 'COMPLETED', 'Critical');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2033, 5047, SYSDATE-2, 'Dr. Gakwaya', 'Ward A', 'Surgery', 'CANCELLED', 'Patient stabilized');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2034, 5049, SYSDATE-1, 'Dr. Kayumba', 'Ward C', 'Cancer', 'COMPLETED', 'Ongoing');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2035, 5050, SYSDATE, 'Dr. Mutoni', 'ICU', 'Trauma', 'IN_PROGRESS', 'Monitoring');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2036, 5003, SYSDATE-30, 'Dr. Gakwaya', 'Ward B', 'Surgery', 'COMPLETED', 'Discharged');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2037, 5007, SYSDATE-28, 'Dr. Kayumba', 'Ward A', 'Anemia', 'COMPLETED', 'Improved');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2038, 5008, SYSDATE-25, 'Dr. Mutoni', 'Maternity', 'Childbirth', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2039, 5012, SYSDATE-22, 'Dr. Gakwaya', 'ICU', 'Accident', 'COMPLETED', 'Critical');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2040, 5017, SYSDATE-18, 'Dr. Kayumba', 'Ward C', 'Malaria', 'COMPLETED', 'Improved');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2041, 5020, SYSDATE-15, 'Dr. Mutoni', 'Ward A', 'Surgery', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2042, 5026, SYSDATE-12, 'Dr. Gakwaya', 'Ward B', 'Anemia', 'COMPLETED', 'Recovery');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2043, 5028, SYSDATE-10, 'Dr. Kayumba', 'Maternity', 'Hemorrhage', 'COMPLETED', 'Critical');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2044, 5031, SYSDATE-8, 'Dr. Mutoni', 'ICU', 'Surgery', 'COMPLETED', 'Stable');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2045, 5034, SYSDATE-6, 'Dr. Gakwaya', 'Ward C', 'Cancer', 'COMPLETED', 'Ongoing');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2046, 5039, SYSDATE-4, 'Dr. Kayumba', 'Ward A', 'Trauma', 'COMPLETED', 'Recovery');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2047, 5041, SYSDATE-2, 'Dr. Mutoni', 'Ward B', 'Surgery', 'COMPLETED', 'No reaction');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2048, 5046, SYSDATE, 'Dr. Gakwaya', 'Maternity', 'Childbirth', 'IN_PROGRESS', 'Monitoring');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2049, 5048, SYSDATE+1, 'Dr. Kayumba', 'ICU', 'Accident', 'SCHEDULED', 'Prep');
INSERT INTO transfusions VALUES (seq_transfusions.NEXTVAL, 2050, 5004, SYSDATE-35, 'Dr. Mutoni', 'Ward A', 'Anemia', 'COMPLETED', 'Discharged');
COMMIT;

INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE, SYSDATE+7, 'HIGH', 85, 20, 45, 'Urgent Call for O+', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE, SYSDATE+3, 'CRITICAL', 90, 5, 10, 'Emergency Appeal', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A+', SYSDATE, SYSDATE+14, 'LOW', 60, 50, 30, 'Monitor', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B+', SYSDATE, SYSDATE+10, 'MEDIUM', 70, 30, 25, 'Schedule Drive', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB+', SYSDATE, SYSDATE+20, 'LOW', 50, 40, 15, 'None', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A-', SYSDATE, SYSDATE+5, 'HIGH', 80, 10, 15, 'Contact Donors', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B-', SYSDATE, SYSDATE+8, 'MEDIUM', 65, 15, 12, 'Call Regulars', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB-', SYSDATE, SYSDATE+12, 'MEDIUM', 60, 8, 6, 'Monitor', SYSDATE);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE-7, SYSDATE, 'HIGH', 88, 18, 40, 'Executed', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE-7, SYSDATE-4, 'CRITICAL', 92, 4, 12, 'Executed', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A+', SYSDATE-7, SYSDATE+7, 'LOW', 62, 52, 28, 'Monitor', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B+', SYSDATE-7, SYSDATE+3, 'MEDIUM', 72, 32, 22, 'Executed', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB+', SYSDATE-7, SYSDATE+13, 'LOW', 55, 42, 12, 'None', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A-', SYSDATE-7, SYSDATE-2, 'HIGH', 82, 12, 18, 'Executed', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B-', SYSDATE-7, SYSDATE+1, 'MEDIUM', 68, 16, 14, 'Executed', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB-', SYSDATE-7, SYSDATE+5, 'MEDIUM', 63, 9, 8, 'Monitor', SYSDATE-7);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE-14, SYSDATE-7, 'HIGH', 84, 15, 38, 'Executed', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE-14, SYSDATE-11, 'CRITICAL', 91, 3, 11, 'Executed', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A+', SYSDATE-14, SYSDATE, 'LOW', 58, 48, 26, 'Monitor', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B+', SYSDATE-14, SYSDATE-4, 'MEDIUM', 71, 28, 20, 'Executed', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB+', SYSDATE-14, SYSDATE+6, 'LOW', 52, 38, 10, 'None', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A-', SYSDATE-14, SYSDATE-9, 'HIGH', 79, 8, 16, 'Executed', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B-', SYSDATE-14, SYSDATE-6, 'MEDIUM', 66, 14, 13, 'Executed', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB-', SYSDATE-14, SYSDATE-2, 'MEDIUM', 61, 7, 7, 'Monitor', SYSDATE-14);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE-21, SYSDATE-14, 'HIGH', 86, 17, 42, 'Executed', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE-21, SYSDATE-18, 'CRITICAL', 93, 4, 13, 'Executed', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A+', SYSDATE-21, SYSDATE-7, 'LOW', 59, 49, 29, 'Monitor', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B+', SYSDATE-21, SYSDATE-11, 'MEDIUM', 69, 29, 23, 'Executed', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB+', SYSDATE-21, SYSDATE-1, 'LOW', 51, 39, 13, 'None', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A-', SYSDATE-21, SYSDATE-16, 'HIGH', 81, 9, 17, 'Executed', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B-', SYSDATE-21, SYSDATE-13, 'MEDIUM', 67, 13, 15, 'Executed', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB-', SYSDATE-21, SYSDATE-9, 'MEDIUM', 62, 8, 9, 'Monitor', SYSDATE-21);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE-30, SYSDATE-23, 'HIGH', 87, 19, 44, 'Executed', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE-30, SYSDATE-27, 'CRITICAL', 94, 6, 14, 'Executed', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A+', SYSDATE-30, SYSDATE-16, 'LOW', 61, 51, 31, 'Monitor', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B+', SYSDATE-30, SYSDATE-20, 'MEDIUM', 73, 31, 24, 'Executed', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB+', SYSDATE-30, SYSDATE-10, 'LOW', 53, 41, 14, 'None', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A-', SYSDATE-30, SYSDATE-25, 'HIGH', 83, 11, 19, 'Executed', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B-', SYSDATE-30, SYSDATE-22, 'MEDIUM', 64, 12, 11, 'Executed', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB-', SYSDATE-30, SYSDATE-18, 'MEDIUM', 59, 6, 5, 'Monitor', SYSDATE-30);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE-60, SYSDATE-53, 'HIGH', 85, 20, 45, 'Executed', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE-60, SYSDATE-57, 'CRITICAL', 90, 5, 10, 'Executed', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A+', SYSDATE-60, SYSDATE-46, 'LOW', 60, 50, 30, 'Monitor', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B+', SYSDATE-60, SYSDATE-50, 'MEDIUM', 70, 30, 25, 'Executed', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB+', SYSDATE-60, SYSDATE-40, 'LOW', 50, 40, 15, 'None', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'A-', SYSDATE-60, SYSDATE-55, 'HIGH', 80, 10, 15, 'Executed', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'B-', SYSDATE-60, SYSDATE-52, 'MEDIUM', 65, 15, 12, 'Executed', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'AB-', SYSDATE-60, SYSDATE-48, 'MEDIUM', 60, 8, 6, 'Monitor', SYSDATE-60);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O+', SYSDATE-90, SYSDATE-83, 'HIGH', 89, 16, 41, 'Executed', SYSDATE-90);
INSERT INTO shortage_predictions VALUES (seq_shortage_pred.NEXTVAL, 'O-', SYSDATE-90, SYSDATE-87, 'CRITICAL', 95, 2, 9, 'Executed', SYSDATE-90);
COMMIT;

INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'INSERT', '1001', NULL, 'New Donor', 'admin', SYSDATE-100, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'INSERT', '5001', NULL, 'New Unit', 'lab_tech', SYSDATE-10, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'UPDATE', '1', 'Temp: 3.5', 'Temp: 4.0', 'sensor_sys', SYSDATE, '10.0.0.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'INSERT', '3001', NULL, 'New Transfusion', 'doctor', SYSDATE-5, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'patients', 'UPDATE', '2001', 'O+', 'O+', 'nurse', SYSDATE-9, '192.168.1.15', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'DELETE', '1051', 'Donor Data', NULL, 'admin', SYSDATE-1, '192.168.1.1', 'BLOCKED');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'UPDATE', '5004', 'AVAILABLE', 'EXPIRED', 'system', SYSDATE-25, '10.0.0.2', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'INSERT', '2', NULL, 'New Item', 'lab_tech', SYSDATE-20, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'UPDATE', '1004', 'ELIGIBLE', 'DEFERRED', 'doctor', SYSDATE-60, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'UPDATE', '3004', 'SCHEDULED', 'IN_PROGRESS', 'nurse', SYSDATE-1, '192.168.1.15', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'shortage_predictions', 'INSERT', '1', NULL, 'New Pred', 'system', SYSDATE, '10.0.0.2', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'INSERT', '1002', NULL, 'New Donor', 'admin', SYSDATE-90, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'INSERT', '5002', NULL, 'New Unit', 'lab_tech', SYSDATE-20, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'UPDATE', '3', 'Check Pending', 'Awaiting Tests', 'lab_tech', SYSDATE-2, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'patients', 'INSERT', '2002', NULL, 'New Patient', 'reception', SYSDATE-20, '192.168.1.10', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'INSERT', '3002', NULL, 'New Transfusion', 'doctor', SYSDATE-10, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'UPDATE', '1010', 'ELIGIBLE', 'PERMANENT_DEFERRED', 'doctor', SYSDATE-30, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'UPDATE', '5017', 'TESTING', 'FAILED', 'lab_tech', SYSDATE-15, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'DELETE', '55', 'Old Stock', NULL, 'admin', SYSDATE-5, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'audit_logs', 'DELETE', '1', 'Log Data', NULL, 'hacker', SYSDATE, '192.168.1.99', 'BLOCKED');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'INSERT', '1003', NULL, 'New Donor', 'admin', SYSDATE-80, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'INSERT', '5003', NULL, 'New Unit', 'lab_tech', SYSDATE-2, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'patients', 'INSERT', '2003', NULL, 'New Patient', 'reception', SYSDATE-5, '192.168.1.10', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'INSERT', '3003', NULL, 'New Transfusion', 'doctor', SYSDATE-2, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'UPDATE', '5', 'Temp: 3.8', 'Temp: 3.8', 'sensor_sys', SYSDATE, '10.0.0.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'UPDATE', '1014', 'ELIGIBLE', 'DEFERRED', 'nurse', SYSDATE-100, '192.168.1.15', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'UPDATE', '5010', 'AVAILABLE', 'ISSUED', 'nurse', SYSDATE-30, '192.168.1.15', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'patients', 'UPDATE', '2004', 'Ward A', 'Ward B', 'nurse', SYSDATE-1, '192.168.1.15', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'shortage_predictions', 'INSERT', '2', NULL, 'New Pred', 'system', SYSDATE, '10.0.0.2', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'INSERT', '1005', NULL, 'New Donor', 'admin', SYSDATE-150, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'INSERT', '5005', NULL, 'New Unit', 'lab_tech', SYSDATE-5, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'INSERT', '3005', NULL, 'New Transfusion', 'doctor', SYSDATE, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'INSERT', '6', NULL, 'New Item', 'lab_tech', SYSDATE-5, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'UPDATE', '1001', 'Address: Old', 'Address: New', 'admin', SYSDATE-50, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'UPDATE', '5031', 'TESTING', 'FAILED', 'lab_tech', SYSDATE-10, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'patients', 'DELETE', '2005', 'Patient Data', NULL, 'nurse', SYSDATE, '192.168.1.15', 'BLOCKED');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'INSERT', '1006', NULL, 'New Donor', 'admin', SYSDATE-60, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'INSERT', '5006', NULL, 'New Unit', 'lab_tech', SYSDATE-5, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'UPDATE', '7', 'Quarantine', 'Awaiting Tests', 'lab_tech', SYSDATE-1, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'UPDATE', '3006', 'COMPLETED', 'COMPLETED', 'doctor', SYSDATE-15, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'shortage_predictions', 'UPDATE', '1', 'LOW', 'MEDIUM', 'system', SYSDATE, '10.0.0.2', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'UPDATE', '1007', 'M', 'M', 'admin', SYSDATE-120, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'UPDATE', '5041', 'AVAILABLE', 'EXPIRED', 'system', SYSDATE-25, '10.0.0.2', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'patients', 'INSERT', '2006', NULL, 'New Patient', 'reception', SYSDATE-1, '192.168.1.10', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'transfusions', 'INSERT', '3007', NULL, 'New Transfusion', 'doctor', SYSDATE-14, '192.168.1.20', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'donors', 'INSERT', '1008', NULL, 'New Donor', 'admin', SYSDATE-40, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'blood_units', 'INSERT', '5008', NULL, 'New Unit', 'lab_tech', SYSDATE-40, '192.168.1.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'inventory', 'DELETE', '5008', 'Expired', NULL, 'admin', SYSDATE-5, '192.168.1.1', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'system_config', 'UPDATE', 'Backup_Config', 'Daily', 'Weekly', 'system', SYSDATE-1, '10.0.0.5', 'SUCCESS');
INSERT INTO audit_logs VALUES (seq_audit_logs.NEXTVAL, 'user_sessions', 'INSERT', 'admin_session_101', NULL, 'New Login Session', 'admin', SYSDATE, '192.168.1.1', 'SUCCESS');
COMMIT;

-- Insert Rwanda Public Holidays (2025-2026)
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'New Year''s Day', TO_DATE('2025-01-01', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Genocide Memorial Day', TO_DATE('2025-04-07', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Labour Day', TO_DATE('2025-05-01', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Independence Day', TO_DATE('2025-07-01', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Liberation Day', TO_DATE('2025-07-04', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Umuganura Day', TO_DATE('2025-08-02', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Christmas Day', TO_DATE('2025-12-25', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Boxing Day', TO_DATE('2025-12-26', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);

-- 2026 Holidays
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'New Year''s Day 2026', TO_DATE('2026-01-01', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Genocide Memorial Day 2026', TO_DATE('2026-04-07', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);
INSERT INTO public_holidays VALUES (seq_holidays.NEXTVAL, 'Labour Day 2026', TO_DATE('2026-05-01', 'YYYY-MM-DD'), 'Rwanda', 'Y', SYSDATE);

COMMIT;
