-- Create sequences for automatic primary key generation
CREATE SEQUENCE seq_donors START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_blood_units START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE seq_inventory START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_patients START WITH 2001 INCREMENT BY 1;
CREATE SEQUENCE seq_transfusions START WITH 3001 INCREMENT BY 1;
CREATE SEQUENCE seq_shortage_pred START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_audit_logs START WITH 1 INCREMENT BY 1;